//////////////////////////////////////////////////////////////////////////////
//
// Copyright 2026 Autodesk, Inc. All rights reserved.
//
// Use of this software is subject to the terms of the Autodesk license
// agreement provided at the time of installation or download, or which
// otherwise accompanies this software.
//
//////////////////////////////////////////////////////////////////////////////

#pragma once
#include "../Core/SimAttribute.h"
#include "../SimTypeDefs.h"
#include <vector>

// THIS CLASS WILL BE VISIBLE TO AN API CLIENT.
// THIS HEADER FILE WILL BE GENERATED FROM NIDL.
#include "../../Core/OSMacros.h"

#ifdef SIMXINTERFACE_EXPORTS
# ifdef __COMPILING_ADSK_SIM_CONTACT_CPP__
# define ADSK_SIM_CONTACT_API XI_EXPORT
# else
# define ADSK_SIM_CONTACT_API
# endif
#else
# define ADSK_SIM_CONTACT_API XI_IMPORT
#endif

namespace adsk { namespace sim {

/// !!!!! Warning !!!!!
/// ! This is hidden and not officially supported
/// !!!!! Warning !!!!!
/// 
/// Base class for contacts.
class Contact : public SimAttribute {
public:

    /// The type of contact.
    ContactTypes type() const;

    /// Gets the information if contact is manual vs. autogenerated
    bool isManual() const;

    /// Gets the primary body selection
    std::vector<core::Ptr<core::Base>> primaryEntities() const;

    /// Gets the secondary body selection
    std::vector<core::Ptr<core::Base>> secondaryEntities() const;

    ADSK_SIM_CONTACT_API static const char* classType();
    ADSK_SIM_CONTACT_API const char* objectType() const override;
    ADSK_SIM_CONTACT_API void* queryInterface(const char* id) const override;
    ADSK_SIM_CONTACT_API static const char* interfaceId() { return classType(); }

private:

    // Raw interface
    virtual ContactTypes type_raw() const = 0;
    virtual bool isManual_raw() const = 0;
    virtual core::Base** primaryEntities_raw(size_t& return_size) const = 0;
    virtual core::Base** secondaryEntities_raw(size_t& return_size) const = 0;
    virtual void placeholderContact0() {}
    virtual void placeholderContact1() {}
    virtual void placeholderContact2() {}
    virtual void placeholderContact3() {}
    virtual void placeholderContact4() {}
    virtual void placeholderContact5() {}
    virtual void placeholderContact6() {}
    virtual void placeholderContact7() {}
    virtual void placeholderContact8() {}
    virtual void placeholderContact9() {}
    virtual void placeholderContact10() {}
    virtual void placeholderContact11() {}
    virtual void placeholderContact12() {}
    virtual void placeholderContact13() {}
    virtual void placeholderContact14() {}
    virtual void placeholderContact15() {}
    virtual void placeholderContact16() {}
    virtual void placeholderContact17() {}
    virtual void placeholderContact18() {}
    virtual void placeholderContact19() {}
    virtual void placeholderContact20() {}
    virtual void placeholderContact21() {}
    virtual void placeholderContact22() {}
    virtual void placeholderContact23() {}
    virtual void placeholderContact24() {}
    virtual void placeholderContact25() {}
    virtual void placeholderContact26() {}
    virtual void placeholderContact27() {}
};

// Inline wrappers

inline ContactTypes Contact::type() const
{
    ContactTypes res = type_raw();
    return res;
}

inline bool Contact::isManual() const
{
    bool res = isManual_raw();
    return res;
}

inline std::vector<core::Ptr<core::Base>> Contact::primaryEntities() const
{
    std::vector<core::Ptr<core::Base>> res;
    size_t s;

    core::Base** p= primaryEntities_raw(s);
    if(p)
    {
        res.assign(p, p+s);
        core::DeallocateArray(p);
    }
    return res;
}

inline std::vector<core::Ptr<core::Base>> Contact::secondaryEntities() const
{
    std::vector<core::Ptr<core::Base>> res;
    size_t s;

    core::Base** p= secondaryEntities_raw(s);
    if(p)
    {
        res.assign(p, p+s);
        core::DeallocateArray(p);
    }
    return res;
}
}// namespace sim
}// namespace adsk

#undef ADSK_SIM_CONTACT_API