//////////////////////////////////////////////////////////////////////////////
//
// Copyright 2026 Autodesk, Inc. All rights reserved.
//
// Use of this software is subject to the terms of the Autodesk license
// agreement provided at the time of installation or download, or which
// otherwise accompanies this software.
//
//////////////////////////////////////////////////////////////////////////////

#pragma once
#include "../Operations/OperationBase.h"
#include <string>

// THIS CLASS WILL BE VISIBLE TO AN API CLIENT.
// THIS HEADER FILE WILL BE GENERATED FROM NIDL.
#include "../../Core/OSMacros.h"

#ifdef CAMXINTERFACE_EXPORTS
# ifdef __COMPILING_ADSK_CAM_ADDITIVEFEAOPERATION_CPP__
# define ADSK_CAM_ADDITIVEFEAOPERATION_API XI_EXPORT
# else
# define ADSK_CAM_ADDITIVEFEAOPERATION_API
# endif
#else
# define ADSK_CAM_ADDITIVEFEAOPERATION_API XI_IMPORT
#endif

namespace adsk { namespace cam {

/// !!!!! Warning !!!!!
/// ! This is in preview state; please see the help for more info
/// !!!!! Warning !!!!!
/// 
/// The AdditiveFEAOperation represents a finite element analysis for
/// metal additive manufacturing processes.  The inherited
/// generateToolpath() method can only be called if the Autodesk Fusion
/// Manufacturing Extension is active.
class AdditiveFEAOperation : public OperationBase {
public:

    /// Contents of the human-readable log file generated by the solver.
    /// This property can be fetched during execution to monitor
    /// progress, or after execution is finished to confirm success or
    /// troubleshoot errors.
    std::string logFileContents() const;

    /// Contents of the machine-readable simsignal file generated by
    /// the solver.  Each line of the file is a JSON object.  These
    /// signals are meant to be more stable than logFileContents(), but
    /// less human-readable.
    std::string signalFileContents() const;

    ADSK_CAM_ADDITIVEFEAOPERATION_API static const char* classType();
    ADSK_CAM_ADDITIVEFEAOPERATION_API const char* objectType() const override;
    ADSK_CAM_ADDITIVEFEAOPERATION_API void* queryInterface(const char* id) const override;
    ADSK_CAM_ADDITIVEFEAOPERATION_API static const char* interfaceId() { return classType(); }

private:

    // Raw interface
    virtual char* logFileContents_raw() const = 0;
    virtual char* signalFileContents_raw() const = 0;
};

// Inline wrappers

inline std::string AdditiveFEAOperation::logFileContents() const
{
    std::string res;

    char* p= logFileContents_raw();
    if (p)
    {
        res = p;
        core::DeallocateArray(p);
    }
    return res;
}

inline std::string AdditiveFEAOperation::signalFileContents() const
{
    std::string res;

    char* p= signalFileContents_raw();
    if (p)
    {
        res = p;
        core::DeallocateArray(p);
    }
    return res;
}
}// namespace cam
}// namespace adsk

#undef ADSK_CAM_ADDITIVEFEAOPERATION_API